// spa/angular/src/app/bloomreach-integration/cms-components/essentials/content/content.component.ts
import { Component } from '@angular/core';

import { BaseComponent } from '../../core/base-component/base-component.interface';
import { ContentComponentWrapper } from '../../core/content-component/content-component.component';
import { ContentService } from '../../../content.service';

@Component({
  selector: 'app-content',
  templateUrl: './content.component.html',
  styleUrls: ['./content.component.css']
})
export class ContentComponent extends ContentComponentWrapper implements BaseComponent {

  constructor(contentService: ContentService) {
    super(contentService);
  }
}

<div className="blog-post has-edit-button" *ngIf="content; else configureComponentBlock" style="position: relative;">
  <app-edit-content *ngIf="content.cmsData" [cmsData]="content.cmsData"></app-edit-content>
  <h2 className="blog-post-title">{{content.document.title}}</h2>
  <p className="blog-post-meta">
    <span className="blog-post-date">{{content.document.date | date}}</span>
    <span className="author"><a href="#pagination">{{content.document.author}}</a></span>
  </p>
  <p>{{content.document.introduction}}</p>
  <figure>
    <img src={{image}} alt={{content.document.title}}/>
  </figure>
  <p [innerHTML]="content.document.content.value"></p>
</div>
<ng-template #configureComponentBlock>Click to configure {{component.type}}</ng-template>

// app-examples/react/src/cms-components/essentials/content.js
import React from 'react';
import { getImageUrl } from '../../utils/image-url';
import { parseDate } from '../../utils/date';

export default class Content extends React.Component {
  render() {
    const content = this.props.content;
    const manageContentButton = this.props.manageContentButton;
    const image = getImageUrl(content.image, this.props.pageModel);

    return (
      <div className="blog-post has-edit-button">
        { manageContentButton && manageContentButton }
        <h2 className="blog-post-title">{content.title}</h2>
        <p className="blog-post-meta">
          { content.date &&
            <span className="blog-post-date">{parseDate(content.date)}</span>
          }
          { content.author &&
            <span className="author"><a href="#pagination">{content.author}</a></span>
          }
        </p>
        { content.introduction &&
          <p>{content.introduction}</p>
        }
        { image &&
          <figure>
            <img src={image} alt={content.title}/>
          </figure>
        }
        { content.content &&
          <p dangerouslySetInnerHTML={{__html: content.content.value}}></p>
        }
      </div>
    );
  }
}
