// app-examples/angular/src/app/bloomreach-integration/cms-components/essentials/news-item/news-item.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { ContentService } from '../../../content.service';

@Component({
  selector: 'app-news-item',
  templateUrl: './news-item.component.html',
  styleUrls: ['./news-item.component.css']
})
export class NewsItemComponent implements OnInit {
  @Input() contentUuid: any;
  content: any;

  constructor(private contentService: ContentService) {}

  ngOnInit() {
    this.getContent(this.contentUuid);
  }

  getContent(contentUuid) {
    this.content = this.contentService.getContentItem(contentUuid);
  }
}

<div className="blog-post has-edit-button">
  <!--{ editContentButton && editContentButton }-->
  <h2 className="blog-post-title">
    <a href={{content.link}}>{{content.document.title}}</a>
  </h2>
  <p className="blog-post-meta">
    <span className="blog-post-date">{{content.document.date | date}}</span>
    <span className="author"><a href="#pagination">{{content.document.author}}</a></span>
  </p>
  <p>{{content.document.introduction}}</p>
</div>

// app-examples/react/src/cms-components/essentials/news-item.js
import React from 'react';
import {parseDate} from "../../utils/date";

export default class NewsItem extends React.Component {
  render () {
    const content = this.props.content;
    const editContentButton = this.props.editContentButton;

    let link;
    if (content._links && content._links.self) {
      link = content._links.self;
    }

    return (
      <div className="blog-post has-edit-button">
        { editContentButton && editContentButton }
        <h2 className="blog-post-title">
          <a href={link}>{content.title}</a>
        </h2>
        <p className="blog-post-meta">
          { content.date &&
            <span className="blog-post-date">{parseDate(content.date)}</span>
          }
          { content.author &&
            <span className="author"><a href="#pagination">{content.author}</a></span>
          }
        </p>
        { content.introduction &&
          <p>{content.introduction}</p>
        }
      </div>
    );
  }
}
