// spa/angular/src/app/bloomreach-integration/cms-components/core/menu/menu.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { ContentService } from '../../../content.service';
import { getConfigurationForPath } from '../../../utils/get-configuration-for-path';
import getNestedObject from '../../../utils/nested-object';

@Component({
  selector: 'cms-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {
  @Input() configuration: any;
  @Input() path: any;
  menuItems: any;

  constructor(private contentService: ContentService) {
  }

  ngOnInit() {
    // if no path is set, use supplied container configuration
    if (!this.path) {
      this.getSiteMenuItems(this.configuration);
    } else {
      const pageModel = this.contentService.getPageModel();
      const configuration = getConfigurationForPath(this.path, pageModel);
      this.getSiteMenuItems(configuration);
    }
  }

  getSiteMenuItems(configuration) {
    this.menuItems = getNestedObject(configuration, ['models', 'menu', 'siteMenuItems']);
  }
}

<ul class="navbar-nav mr-auto">
  <li class="nav-item" *ngFor="let menuItem of menuItems">
    <a class="nav-link" *ngIf="menuItem._links.site.type === 'internal'" routerLink={{menuItem._links.site.href}}>
      {{menuItem.name | titlecase }}<span *ngIf="menuItem.selected" class="sr-only">(current)</span>
    </a>
    <a class="nav-link" *ngIf="menuItem._links.site.type === 'external'" href={{menuItem._links.site.href}}>
      {{menuItem.name | titlecase}}<span *ngIf="menuItem.selected" class="sr-only">(current)</span>
    </a>
  </li>
</ul>

// app-examples/react/src/cms-components/core/menu.js
import React from 'react';
import { Link } from 'react-router-dom'
import { getConfigurationForPath } from '../../utils/get-configuration-for-path';

export default class CmsMenu extends React.Component {
  renderMenu(configuration, pageModel, preview) {
    return configuration.models.menu.siteMenuItems.map((menuItem) => {
      return (
        <CmsMenuItem configuration={menuItem} preview={preview} key={menuItem.name} />
      )
    });
  }

  render() {
    const pageModel = this.props.pageModel;
    const preview = this.props.preview;

    let configuration;
    // if no path is set, use supplied container configuration
    if (!this.props.path) {
      configuration = this.props.configuration;
    } else {
      configuration = getConfigurationForPath(this.props.path, pageModel);
    }

    if (!configuration || !configuration.models || !configuration.models.menu
      || !configuration.models.menu.siteMenuItems || configuration.models.menu.siteMenuItems.length === 0) {
      return null;
    }

    return (
      <ul className="navbar-nav mr-auto">
        { this.renderMenu(configuration, pageModel, preview) }
      </ul>
    );
  }
}

class CmsMenuItem extends React.Component {
  renderLink (configuration, active) {
    if (configuration._links && configuration._links.site && configuration._links.site.href) {
      if (configuration._links.site.type === 'internal') {
        return (<Link className="nav-link" to={configuration._links.site.href}>{configuration.name}{active}</Link>);
      } else {
        return (<a className="nav-link" href={configuration._links.site.href}>{configuration.name}{active}</a>)
      }
    }
    return null;
  }

  render() {
    const configuration = this.props.configuration;

    if (!configuration) {
      return null;
    }

    let active;
    if (configuration.selected) {
      active = <span className="sr-only">(current)</span>;
    }

    return (
      <li className="nav-item">
        { this.renderLink(configuration, active) }
      </li>
    );
  }
}
