// spa/angular/src/app/bloomreach-integration/cms-components/essentials/news-list/news-list.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { BaseComponent } from '../../core/base-component/base-component.interface';
import getNestedObject from '../../../utils/nested-object';

@Component({
  selector: 'cms-essentials-news-list',
  templateUrl: './news-list.component.html',
  styleUrls: ['./news-list.component.css']
})
export class NewsListComponent implements BaseComponent, OnInit {
  @Input() configuration: any;
  @Input() content: any;
  items: any;

  constructor() { }

  ngOnInit() {
    this.createList();
  }

  createList() {
    this.items = getNestedObject(this.configuration, ['models', 'pageable', 'items']);
  }
}

<div className="row" *ngIf="items; else configureComponentBlock">
  <div className="col-sm-12 news-list">
    <cms-essentials-news-item *ngFor="let item of items" [contentRef]="item"></cms-essentials-news-item>
  </div>
  <nav className="blog-pagination">
    <a className="btn btn-outline-primary disabled" href="#pagination">Older</a>
    <a className="btn btn-outline-secondary disabled" href="#pagination">Newer</a>
  </nav>
</div>
<ng-template #configureComponentBlock>Click to configure {{configuration.label}}</ng-template>

// spa/react/src/cms-components/essentials/news-list.js
import React from 'react';
import Placeholder from '../core/placeholder';
import ContentComponentWrapper from '../core/content-component-wrapper';

export default class NewsList extends React.Component {
  render() {
    const preview = this.props.preview;
    const pageModel = this.props.pageModel;
    const configuration = this.props.configuration;

    // return placeholder if no list is set on component
    let list = undefined;
    if (configuration && configuration.models && configuration.models.pageable && configuration.models.pageable.items
      && configuration.models.pageable.items.length !== 0) {
      list = configuration.models.pageable.items;
    } else if (preview) {
      return (
        <Placeholder componentType={configuration.type} />
      );
    } else {
      // don't render placeholder outside of preview mode
      return null;
    }

    // build list of news articles
    const listItems = list.map((listItem, index) => {
      if (configuration && typeof configuration === 'object' && configuration.constructor === Object) {
        // change type as we want to render the NewsItem component
        const newsItemConfig = {label: 'News Item'};
        if ('$ref' in listItem) {
          return (
            <ContentComponentWrapper documentUuid={listItem.$ref} configuration={newsItemConfig} pageModel={pageModel}
                                     preview={preview} key={index}/>
          );
        }
      }
      console.log('NewsList component configuration is not a map, unexpected format of configuration');
      return null;
    });

    return (
      <div className="row">
        <div className="col-sm-12 news-list">
          {listItems}
        </div>
        <nav className="blog-pagination">
          <a className="btn btn-outline-primary disabled" href="#pagination">Older</a>
          <a className="btn btn-outline-secondary disabled" href="#pagination">Newer</a>
        </nav>
      </div>
    );
  }
}
