// spa/react/src/cms-components/essentials/banner.js
import React from 'react';
import { getImageUrl } from '../../utils/image-url';
import { parseAndRewriteLinks } from '../../utils/link-rewriter';

export default class Banner extends React.Component {
  render() {
    const content = this.props.content;
    const manageContentButton = this.props.manageContentButton;
    const image = getImageUrl(content.image, this.props.pageModel);

    let contentHtml;
    if (content.content && content.content.value) {
      contentHtml = parseAndRewriteLinks(content.content.value);
    }

    return (
      <div className="jumbotron has-edit-button">
        { manageContentButton && manageContentButton }
        { content.title &&
          <h1>{content.title}</h1>
        }
        { image &&
          <figure>
            <img src={image} alt={content.title}/>
          </figure>
        }
        { contentHtml && contentHtml }
        <p><a className="btn btn-primary btn-lg" href="#banner_link">Learn more</a></p>
      </div>
    );
  }
}

// app-examples/angular/src/app/bloomreach-integration/cms-components/essentials/banner/banner.component.ts
import { Component } from '@angular/core';

import { BaseComponent } from '../../core/base-component/base-component.interface';
import { ContentComponentWrapper } from '../../core/content-component/content-component.component';
import { ContentService } from "../../../content.service";

@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.css']
})
export class BannerComponent extends ContentComponentWrapper implements BaseComponent {

  constructor(contentService: ContentService) {
    super(contentService);
  }
}

<div class="jumbotron has-edit-button" *ngIf="content; else configureComponentBlock">
  <app-edit-content *ngIf="content.cmsData" [cmsData]="content.cmsData"></app-edit-content>
  <h1>{{content.document.title}}</h1>
  <figure>
    <img src={{image}} alt={{content.document.title}}/>
  </figure>
  <p [innerHTML]="content.document.content.value"></p>
  <p><a class="btn btn-primary btn-lg" href="#banner_link">Learn more</a></p>
</div>
<ng-template #configureComponentBlock>Click to configure {{component.type}}</ng-template>
