// app-examples/react/src/cms-components/essentials/banner.js
import React from 'react';
import { getImageUrl } from '../../utils/image-url';

export default class Banner extends React.Component {
  render() {
    const content = this.props.componentContent;
    const editContentButton = this.props.editContentButton;
    const imageUrl = getImageUrl( content.image );

    return (
      <div className="jumbotron has-edit-button">
        { editContentButton && editContentButton }
        {content.title &&
          <h1>{content.title}</h1>
        }
        {imageUrl &&
          <figure>
            <img src={imageUrl} alt={content.title}/>
          </figure>
        }
        {content.content &&
          <p dangerouslySetInnerHTML={{__html: content.content.value}}></p>
        }
        <p><a className="btn btn-primary btn-lg" href="#banner_link">Learn more</a></p>
      </div>
    );
  }
}

// spa/angular/src/app/bloomreach-integration/cms-components/essentials/banner/banner.component.ts
import { Component, OnInit } from '@angular/core';

import { BaseComponent } from '../../core/base-component/base-component.interface';
import { ContentComponentWrapper } from '../../core/content-component/content-component.component';
import { ContentService } from '../../../content.service';

@Component({
  selector: 'cms-essentials-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.css']
})
export class BannerComponent extends ContentComponentWrapper implements BaseComponent, OnInit {
  imageUrl: string;

  constructor(contentService: ContentService) {
    super(contentService);
  }

  ngOnInit() {
    super.ngOnInit();
    this.imageUrl = super.getImageUrl();
  }
}

<div class="jumbotron has-edit-button" *ngIf="content; else configureComponentBlock">
  <cms-edit-content *ngIf="content._meta" [metaData]="content._meta"></cms-edit-content>
  <h1>{{content.title}}</h1>
  <figure>
    <img src={{imageUrl}} alt={{content.title}}/>
  </figure>
  <p [innerHTML]="content.content.value"></p>
  <p><a class="btn btn-primary btn-lg" href="#banner_link">Learn more</a></p>
</div>
<ng-template #configureComponentBlock>Click to configure {{configuration.label}}</ng-template>
