// app-examples/react/src/cms-components/essentials/news-item.js
import React from 'react';
import { Link } from 'react-router-dom'
import { parseDate } from "../../utils/date";

export default class NewsItem extends React.Component {
  render () {
    const content = this.props.content;
    const manageContentButton = this.props.manageContentButton;

    let link;
    if (content._links && content._links.site) {
      if (content._links.type === 'internal') {
        link = <Link to={content._links.site}>{content.title}</Link>
      } else {
        link = <a href={content._links.site}>{content.title}</a>
      }
    }

    return (
      <div className="blog-post has-edit-button">
        { manageContentButton && manageContentButton }
        <h2 className="blog-post-title">
          { link && link }
        </h2>
        <p className="blog-post-meta">
          { content.date &&
            <span className="blog-post-date">{parseDate(content.date)}</span>
          }
          { content.author &&
            <span className="author"><a href="#pagination">{content.author}</a></span>
          }
        </p>
        { content.introduction &&
          <p>{content.introduction}</p>
        }
      </div>
    );
  }
}

// spa/angular/src/app/bloomreach-integration/cms-components/essentials/news-item/news-item.component.ts
import { Component, Input, OnInit } from '@angular/core';

import { ContentService } from '../../../content.service';

@Component({
  selector: 'cms-essentials-news-item',
  templateUrl: './news-item.component.html',
  styleUrls: ['./news-item.component.css']
})
export class NewsItemComponent implements OnInit {
  @Input() contentRef: any;
  content: any;

  constructor(private contentService: ContentService) {}

  ngOnInit() {
    this.getContent(this.contentRef);
  }

  getContent(contentRef) {
    if (contentRef && contentRef.$ref) {
      this.content = this.contentService.getContentViaReference(contentRef.$ref);
    }
  }
}

<div className="blog-post has-edit-button" style="position: relative;">
  <cms-edit-content *ngIf="content._meta" [metaData]="content._meta"></cms-edit-content>
  <h2 className="blog-post-title">
    <a *ngIf="content._links.site.type === 'internal'" routerLink={{content._links.site.href}}>{{content.title}}</a>
    <a *ngIf="content._links.site.type !== 'internal'" href={{content._links.site.href}}>{{content.title}}</a>
  </h2>
  <p className="blog-post-meta">
    <span className="blog-post-date">{{content.date | date}}</span>
    <span className="author"><a href="#pagination">{{content.author}}</a></span>
  </p>
  <p>{{content.introduction}}</p>
</div>
